#!/bin/bash
#
# Usage
#   redmine edit [options] <ticket_id>
#
# Description
#   edit a specified ticket.
#
# Options
#   -r <note_id>  quote reply to the specified note
#   -h            show this message
#

show_help() {
	sed -n 2,$[$BASH_LINENO-4]p $BASH_SOURCE | grep "^#" | sed 's/^#/ /'
}

REPLYNOTE=

while [[ $# -gt 0 ]] ; do
	key="$1"
	case $key in
		-r)
			REPLYNOTE="$2"
			shift 2
			;;
		-h)
			show_help
			exit 0
			;;
		*)
			break
			;;
	esac
done

. $THISDIR/tree.sh

ISSUEID=$1

if ! check_ticket_id_format $ISSUEID ; then
	echo "invalid issueid format" >&2
	exit 1
fi

if [[ "$ISSUEID" =~ ^L ]] ; then
	edit_local_ticket $ISSUEID
	exit 0
fi

update_local_cache_task $ISSUEID || exit 1
! check_issue_exist $ISSUEID && echo "issue $ISSUEID not found" && exit 1

update_issue3 $ISSUEID
