#!/bin/bash
#
# Usage
#   redmine new [options]
#
# Description
#
# Options
#   -l            create local ticket
#   -h            show this message
#

show_help() {
	sed -n 2,$[$BASH_LINENO-4]p $BASH_SOURCE | grep "^#" | sed 's/^#/ /'
}

while [[ $# -gt 0 ]] ; do
	key="$1"
	case $key in
		-l)
			LOCALTICKET=true
			shift 1
			;;
		-h)
			show_help
			exit 0
			;;
		*)
			break
			;;
	esac
done

if [ "$LOCALTICKET" ] ; then
	ISSUEID="$(generate_local_ticket_id)"
else
	ISSUEID=new
fi

mkdir -p $TMPD/$ISSUEID
prepare_draft_file $ISSUEID || exit 1
update_issue $ISSUEID || exit 1
