#!/bin/bash
#
# Usage
#   redmine relation [option] <idspec> [...]
#   redmine relation [option] -d <id|idspec> [...]
#
# Description
#   relations are notated by <idspec> like follows:
#
#     (issue1)->(issue2)   issue1 precedes issue2
#     (issue1)<-(issue2)   issue1 follows issue2
#     (issue1)-o(issue2)   issue1 blocks issue2
#     (issue1)o-(issue2)   issue1 blocked issue2
#     (issue1)-c(issue2)   issue1 copied_to issue2
#     (issue1)c-(issue2)   issue1 copied_from issue2
#     (issue1)-(issue2)    issue1 relates issue2
#     (issue1)=>(issue2)   issue1 duplicates issue2
#     (issue1)<=(issue2)   issue1 duplicated issue2
#
# Options
#   -d            delete relation
#   -l            list relations
#   -h            show this message

show_help() {
	sed -n 2,$[$BASH_LINENO-4]p $BASH_SOURCE | grep "^#" | sed 's/^#/ /'
}

DELETE=
LIST=
while [[ $# -gt 0 ]] ; do
	key="$1"
	case $key in
		-d)
			DELETE=true
			shift 1
			;;
		-l)
			LIST=true
			shift 1
			;;
		-h)
			show_help
			return 0
			;;
		*)
			# echo "invalid option $key"
			break
			;;
	esac
done

if [ ! "$@" ] && [ ! "$LIST" ] ; then
	echo "no IDSPEC given."
	show_help
	return 1
fi

update_local_cache > /dev/null 2>&1 || exit 1
generate_relations_cache > $TMPDIR/relation.tsv
if [ "$DELETE" = true ] ; then
	for string in $@ ; do
		delete_one_relation $string
	done
elif [ "$LIST" = true ] ; then
	expand -t12 $TMPDIR/relation.tsv
else
	for string in $@ ; do
		create_one_relation $string
	done
fi
