#!/bin/bash
#
# Usage
#   redmine relation [option] <idspec> [...]
#   redmine relation [option] -d <id|idspec> [...]
#
# Description
#   ...
#
#   idspec is ...
#
# Options
#   -d            delete relation
#   -l            list relations
#   -h            show this message

show_help() {
	sed -n 2,$[$BASH_LINENO-4]p $BASH_SOURCE | grep "^#" | sed 's/^#/ /'
}

DELETE=
LIST=
while [[ $# -gt 0 ]] ; do
	key="$1"
	case $key in
		-d)
			DELETE=true
			shift 1
			;;
		-l)
			LIST=true
			shift 1
			;;
		-h)
			show_help
			exit 0
			;;
		*)
			# echo "invalid option $key"
			break
			;;
	esac
done

if [ ! "$@" ] && [ ! "$LIST" ] ; then
	echo "no IDSPEC given."
	show_help
	exit 1
fi

update_local_cache > /dev/null 2>&1 || exit 1
generate_relations_cache > $TMPDIR/relation.tsv
if [ "$DELETE" = true ] ; then
	for string in $@ ; do
		delete_one_relation $string
	done
elif [ "$LIST" = true ] ; then
	expand -t12 $TMPDIR/relation.tsv
else
	for string in $@ ; do
		create_one_relation $string
	done
fi
