#!/bin/bash
#
# Usage
#   redmine remove [options] <ticket_id>
#
# Description
#   Remove the specified ticket from Redmine server, so you have to be
#   careful not to lose data. The data backup will be saved on server
#   under cache directory ($RM_CONFIG/edit_memo/$ticketid).
#
# Options
#   -h            show this message
#
# TODO:
#  - how do we find the reomved issues on server-side (by other users)

show_help() {
	sed -n 2,$[$BASH_LINENO-4]p $BASH_SOURCE | grep "^#" | sed 's/^#/ /'
}

while [[ $# -gt 0 ]] ; do
	key="$1"
	case $key in
		-h)
			show_help
			exit 0
			;;
		*)
			break
			;;
	esac
done

ISSUEID=$1

if ! check_ticket_id_format $ISSUEID ; then
	echo "invalid issueid format" >&2
	exit 1
fi

if [[ "$ISSUEID" =~ ^L ]] ; then
	echo "Removing local ticket not supported. (maybe you don't have to do this)"
	exit 0
fi

update_local_cache_task $ISSUEID || exit 1
! check_issue_exist $ISSUEID && echo "issue $ISSUEID not found" && exit 1

echo "You really remove issue $ISSUEID (subject: $(issueid_to_subject $ISSUEID))? (y: yes, n: no)"
read input
if [ "$input" != y ] && [ "$input" != Y ] ; then
	echo cancelled
	return 0
fi

remove_ticket $ISSUEID || exit 1
rmeove_ticket_from_local_cache $ISSUEID
echo "successfully removed issue $ISSUEID, and the data is saved on $TMPD/$ISSUEID/"
