#!/bin/bash
#
# Usage
#   redmine show [options] <ticket_id>
#
# Description
#
# Options
#   -n            display notes
#   -h            show this message
#

# TODO: support local ticket

show_help() {
	sed -n 2,$[$BASH_LINENO-4]p $BASH_SOURCE | grep "^#" | sed 's/^#/ /'
}

SHOW_JOURNALS=

while [[ $# -gt 0 ]] ; do
	key="$1"
	case $key in
		-n)
			SHOW_JOURNALS=true
			shift
			;;
		-h)
			show_help
			exit 0
			;;
		*)
			break
			;;
	esac
done

ISSUEID=$1

if ! check_ticket_id_format $ISSUEID ; then
	echo "invalid issueid format" >&2
	exit 1
fi

if [[ "$ISSUEID" =~ ^L ]] ; then
	cat $TMPD/$ISSUEID/draft.md
	exit
fi

update_local_cache_task $ISSUEID || exit 1
! check_issue_exist $ISSUEID && echo "issue $ISSUEID not found" && exit 1

tmpfile=$TMPDIR/tmp.show.txt
__curl "/issues.json" $TMPDIR/tmp.show "&issue_id=$ISSUEID&include=relations&status_id=*"
convert_to_draft_from_json $ISSUEID $TMPDIR/tmp.show $TMPDIR/tmp.show.txt

if [ "$SHOW_JOURNALS" ] ; then
	echo >> $tmpfile
	jq -r '.journals[] | select(.notes != "") | "===> \(.user.name) on \(.created_on)\n\(.notes)"' $tmpjson >> $tmpfile
fi

# TODO: use cat if the standard output is connected to pipe
less $tmpfile
