#!/bin/bash
#
# Usage
#   redmine update [options] <ticket_id>
#
# Description
#
# Options
#   -h            show this message
#

show_help() {
	sed -n 2,$[$BASH_LINENO-4]p $BASH_SOURCE | grep "^#" | sed 's/^#/ /'
}

while [[ $# -gt 0 ]] ; do
	key="$1"
	case $key in
		-h)
			show_help
			exit 0
			;;
		*)
			break
			;;
	esac
done

# TODO: support pagination (当面は 1 ページ以内に収まる)

__curl "/projects.json" $RM_CONFIG/projects.json "limit=100"
for id in $(jq -r ".projects[].id" $RM_CONFIG/projects.json) ; do
	__curl "/projects/$id/versions.json" "$RM_CONFIG/versions/${id}.json" "limit=100"
done

__curl "/enumerations/issue_priorities.json" "$RM_CONFIG/priorities.json" "limit=100"

__curl "/trackers.json" "$RM_CONFIG/trackers.json" "limit=100"

__curl "/users.json" "$RM_CONFIG/users.json" "limit=100"

__curl "/issue_statuses.json" "$RM_CONFIG/issue_statuses.json" "limit=100"
